INCLUDE "emu8086.inc"

JMP START

DATA SEGMENT
    PAKET  DW    0      ;JUMLAH PAKET YANG AKAN TRITRANSFER
    N       DW    0         ;JUMLAH PAKET YANG TELAH DITRANSFER DAN MENDETEKSI SIKLUS 128
    N2      DW    0         ;JUMLAH TRANSMISI  
    MSG1    DW   "Masukkan jumlah paket: ",0
    MSG2    DW    "Jumlah Transmisi: ",0
   
DATA ENDS  

CODE SEGMENT

ASSUME DS:DATA CS:CODE 

START:
       MOV CX, DATA         ;DEKLARASIKAN DATA SEGMENT
	   MOV DS, CX   
	   DEFINE_SCAN_NUM
       DEFINE_PRINT_STRING
       DEFINE_PRINT_NUM
       DEFINE_PRINT_NUM_UNS 
       DEFINE_CLEAR_SCREEN  
       
	   LEA SI,MSG1
	   CAll PRINT_STRING
	   CALL SCAN_NUM
	   MOV PAKET,CX
	   

LOOP2: INC N2               ;MENAMBAH JUMLAH TRANSMISI YANG DILAKUKAN
       INC N                ;MENAMBAH JUMLAH PAKET YANG TELAH DITRANSFER
       DEC PAKET            ;MENGURANGI JUMLAH PAKET YANG TERSISA UNTUK DITRANSFER
       
       CMP N,64
       JB  ELSE             ;JIKA JUMLAH PAKET YANG DITRANSFER KURANG DARI 64    
       
       INC N
       DEC PAKET 
       JMP DONE 
       
ELSE:  MOV CX,N
       SHL N,1
       SUB N,CX             ;MENGURANGI NILAI N SEBESAR NILAI CX
       MOV CX,N 
       CMP CX,PAKET         ;MEMERIKSA APAKAH JUMLAH PAKET YANG TERSISA KURANG DARI JUMLAH PAKET YANG TELAH DITRANSFER
       JA  BREAK
       JE  BREAK
       SUB PAKET,CX
       ADD N,CX             ;MENGEMBALIKAN NILAI N KE KEADAAN SEMULA
       
       



DONE:  CMP  PAKET,0
       JB   BREAK
       JE   BREAK
       CMP  N,128
       JNE  END
       MOV  N,0
END:   JMP  LOOP2  

BREAK: PRINT 0AH            ;CETAK LINE BARU
       PRINT 0DH            ;CETAK CARRIAGE RETURN
       LEA  SI,MSG2
       CALL PRINT_STRING
       MOV  AX,N2   
       CALL PRINT_NUM_UNS       
	        
	       
CODE ENDS

END START

ret